# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres:11.5
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432